Timeout jwt
mongoose-os-libs/gcp pull request #3
Opened 2018-08-28 19:14 UTC by Alxandr

I'm new to a lot of this, so I'd like some early review if anyone could provide it. This is not yet tested, so it might very well segfault (I'm doing testing atm).

Closes #2

2018-08-28 20:39 UTC, rojer requested changes
a few stylistic changes, otherwise LGTM.
also please run `clang-format` with [this config](https://github.com/cesanta/mongoose-os/blob/master/.clang-format). on the file.

2018-08-28 20:39 UTC, rojer commented on src/mgos_gcp.c
> +  struct gcp_state *state = malloc(sizeof(*state));
always use `calloc` to allocate structs

2018-08-28 20:39 UTC, rojer commented on src/mgos_gcp.c
> +  state->jwt_timeout = 0;
use MGOS_INVALID_TIMER_ID instead of 0, here and in other places

2018-08-28 20:39 UTC, rojer commented on src/mgos_gcp.c
> +  LOG(LL_DEBUG, ("Disconnecting global MQTT connection due to JWT timeout."));
make it INFO level and change wording somewhat: "Dropping MQTT connection due to imminent token expiration"

2018-08-28 20:39 UTC, rojer commented on src/mgos_gcp.c
> +  mgos_timer_id jwt_timeout;
`token_ttl_timer_id`

2018-08-28 20:39 UTC, rojer commented on src/mgos_gcp.c
> +  state->jwt_timeout = mgos_set_timer((ttl * 1000) - 30000, 0,
`(ttl - 30) * 1000`

2018-08-28 20:58 UTC, Alxandr commented
Updated based on comments, however the timer does not seem to trigger. Any idea what could be causing this?

2018-08-28 21:16 UTC, Alxandr commented
I figured it out. I had setup of my project wrong, so I was building using the normal gcp version, and not my fork. I've fixed it, and can see that it's working (just setting the `ttl` to 120).

2018-08-29 15:31 UTC, Alxandr commented
Having run this for a night, I don't see any problems. So it seems the issue is solved :)

2018-08-29 22:44 UTC, rojer commented
ok, this looks good, integrating. thank you!

note: you will see this PR closed without merging and a different commit will appear instead.

2018-08-30 06:32 UTC, closed without merging

2018-08-30 13:02 UTC, Alxandr commented
Out of curiosity; why on earth are you commiting other peoples code as your own?

2018-08-30 15:34 UTC, rojer commented
@Alxandr this is because commits first go to our internal monolithic repo and then get published to individual lib repos by a bot. we don't merge PRs into external repos directly because then they'll get out of sync and we'll have merge conflicts during publishing, which bot cannot resolve.

2018-08-30 22:14 UTC, Alxandr commented
So what you're saying is that you've made a system, in which contributors do not get attribution as part of the history? Doesn't that seem a bit disingenuous? Now, honestly, regarding this code here, I don't really care, and you're free to use it however you like; but I was not asked about this. There are no contributor guidelines that state that if you make a PR we will just copy the code and claim it as our own. From my perspective at least, if you want contributors, I'd strongly suggest rethinking this strategy (and/or any automation you've built that enforces it).

2018-08-30 22:29 UTC, rojer commented
@Alxandr we always reference the original PR in the description, and usually i also explicitly credit the author by @-mention - see e.g. https://github.com/cesanta/mongoose-os/commit/c9d76ac82f1058cd4a14de84da3964b37aa4fe1e
i forgot to do it this time, my bad.

this system is what we had in place since day 1, even before we started accepting contributions and all work was done in house.
it is our plan to stop this publishing system, and we are working towards that, but it is not yet possible (there is a legacy internal CI system that depends on having everything in one repo).
please bear with us here, i agree this is sub-optimal.

2018-08-30 22:37 UTC, Alxandr commented
Yeah, as said, in this case I don't really care, cause it was a one off fix. But if I was going to contribute any significant time to a project, it would definitely be off-putting.